GEOS-ESM/GEOSgcm_App

- gcm_archive.j
- gcm_archive_CPLFCST.j
- gcm_convert.j
- gcm_forecast.tmpl
- gcm_moveplot.j
- gcm_plot.tmpl
- gcm_post.j
- gcm_post_full_CPLFCST.j
- gcm_post_part_CPLFCST.j
- gcm_quickstat.j
- gcm_regress.j
- gcm_run.j
- gcm_run_CPLFCST360S2S.j
- gcm_run_CPLFCST360S2Sall.j
- gcm_setup
- gcm_stats.j
- gmichem_setup
As much of the ADAS bits of GEOS rely on g5_modules, we revert files
back to source'ing it
> Restore g5_modules use

- CMakeLists.txt
- scm_setup
* Install the script in `install/bin`
* The script now is run *from* `install/bin` and seems to work.
> Fixes #11. Gets scm_setup working

- .github/CODEOWNERS
- CMakeLists.txt
- HISTORY_GMICHEM.rc.tmpl
- gcm_run.j
- gmichem_setup
- stratchem_setup
This should establish a history.
> Manually merge develop into dev/MAPL-2.0

- gcm_regress.j
> fix gcm_regress.j script

- AGCM.rc.tmpl
- HISTORY.AOGCM.rc.tmpl
- gcm_run.j
Fixes #42 This branch should be tested together with feature/yury/s2s3-merge in GEOSgcm_GridComp and GMAO_Shared.
> Merged with S2S-3 tag

- AGCM.rc.tmpl
- gcm_forecast.setup
- gcm_forecast.tmpl
- gcm_regress.j
- gcm_run.j
- gcm_setup
Must be taken together with pull requests [GEOSgcm_GridComp #168](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/168) and [GEOSchem_GridComp](https://github.com/GEOS-ESM/GEOSchem_GridComp/pull/42).
> Updates for new way of running IAU and model setup

- AGCM.rc.tmpl
- gcm_forecast.setup
- gcm_forecast.tmpl
- gcm_regress.j
- gcm_run.j
- gcm_setup
Reverts GEOS-ESM/GEOSgcm_App#72
> Revert "Updates for new way of running IAU and model setup"

- AGCM.rc.tmpl
- gcm_forecast.setup
- gcm_forecast.tmpl
- gcm_regress.j
- gcm_run.j
- gcm_setup
Reverts GEOS-ESM/GEOSgcm_App#75
> Revert "Revert "Updates for new way of running IAU and model setup""

- AGCM.rc.tmpl
This will help in nightly tests.
> Signify MERRA2 Replay lines for scripting

- gcm_setup
* Remove duplicate BCSDIR at NCCS
* Use spaces not tabs
> Clean up gcm_setup

- .AGCM_VERSION
- CMakeLists.txt
- gcm_emip.setup
- gcm_forecast.setup
- gcm_plot.tmpl
- gcm_run.j
- gcm_setup
- geoschemchem_setup
- gmichem_setup
- stratchem_setup
Also, use the CMake Project number to fill `.AGCM_VERSION`
Related to GEOS-ESM/GMAO_Shared#78
> Use sbatch at NCCS, qsub at NAS

- geoschemchem_setup
- gmichem_setup
- stratchem_setup
ZeroDiff for PCHEM cases; this makes the StratChem, GMI and GEOS-Chem setup scripts up-to-date.
> Brought the chem setup scripts in line with gcm_setup

- CMakeLists.txt
Sigh. Forgot to remove one of my debugging `message()` lines. Sorry!
> Update CMakeLists.txt: Remove debug print

- gcm_forecast.setup
Enables forecast length to work correctly
> Bug fix in gcm_forecast.setup

- gcm_setup
- geoschemchem_setup
- gmichem_setup
- stratchem_setup
A possible band aid fix for now. @wmputman approve if you think this is a possible solution in the short term. Also, what about L137 - same as L72?
> Update Aerosol Chemistry BCs CHMDIR variable to match vertical levels

- geoschemchem_setup
- gmichem_setup
- stratchem_setup
This PR brings in some edits from `gcm_setup` into the `chem_setup` scripts.
> Sync up chem_setup scripts with gcm_setup

- gcm_setup
- geoschemchem_setup
- gmichem_setup
- stratchem_setup
This also needs ESMA_cmake v3.1.0 for full use (needed to detect AWS).
ETA: Now in GEOSgcm `main`!
> Add section for AWS SLURM

- scm_setup
Per request of @narnold1, this PR should allow for 91, 137 and 181 level runs of SCM.
> Allow more levels for scm

- geoschemchem_setup
Per @mmanyin I missed a `if CUBED == TRUE` bit of code.
> Fix geoschemchem_setup

- gcm_run.j
This is a very minor thing, but it is annoying if you need to change. If you uncomment, the line is incomplete. 😄
> Restore missing forward-slash

- CODE_OF_CONDUCT.md
Add `CODE_OF_CONDUCT` based on [Contributor Covenant v2.0](https://www.contributor-covenant.org/).
I figured since we've turned on Discussions in GEOSgcm_App, we should add a Code of Conduct.
> Add CODE_OF_CONDUCT.md [skip ci]

- gcm_convert.j
- gcm_regress.j
- gcm_run.j
- gcm_setup
- geoschemchem_setup
- gmichem_setup
- stratchem_setup
This PR adds support for the new Rome nodes at NAS named like `r201c2t1n4`
> Add support for rome node format

- GEOSgcm.F90
This PR should be approved after https://github.com/GEOS-ESM/MAPL/pull/846
> follow MAPL's change to add a new MAPL_CapOptions constructor

- gcm_run.j
Closes #218 
My first attempt at checking for MERRA2OX consistency. I'll probably keep this as a draft until @bena-nasa, @sdrabenh, and myself can really shake it out.
> Attempt to detect MERRA2OX Date violation

- GEOSgcm.F90
Changes MAPL FLAP function call to match changes/simplifications that will be introduced in MAPL V3.
> MAPL V3 FLAP usage simplification

- AGCM.rc.tmpl
- gcm_forecast.tmpl
- gcm_regress.j
- gcm_run.j
- gcm_setup
- geoschemchem_setup
- gmichem_setup
- scm_setup
- stratchem_setup
This PR adds support for AMIP.20C ExtData. It repurposes the old MERRA-2 magic date code for this purpose, with the new magic date being 2000-03-01.
Keeping draft until it can be tested.
> Add support for AMIP.20C

- gcm_setup
- geoschemchem_setup
- gmichem_setup
- stratchem_setup
This PR sets the default MOM6 resolution when C12 is selected to 72x36
It's a bit hacky, but good for now.
> Default to 72x36 for c12 mom6

- gmichem_setup
GMI setup script has a bug fix related to the Data Ocean case.
It also performs better edits on the Chem_Registry.rc files under RC and RC/AMIP.
This PR is zero-diff for all cases (except GMI setup).
> update for gmichem_setup

- AGCM.rc.tmpl
This PR is to keep GEOS-ESM/GEOSgcm_App in sync with the development of IGNI GC in GEOS-ESM/GEOSgcm_GridComp.
> Add IGNI GC restart files

- .circleci/config.yml
We now have extra spend now on CircleCI, so I'm enabling a coupled run test along with the usual AMIP test.
> Enable coupled run test

- .github/workflows/enforce-labels.yml
- .github/workflows/push-to-develop.yml
This PR just updates some github actions to the current versions.
> Update github actions to latest versions

- gcm_regress.j
This PR attempts to add support for comparing the `mkiau_checkpoint` files that @sdrabenh just exposed to me can exist.
> Add regress support for comparing mkiau checkpoints

- HISTORY_R21C.rc.tmpl
> M21C updates

- linkbcs.tmpl
The purpose of this PR is to resolve issue #622
> Bugfix for issue #622

- HISTORY_R21C.rc.tmpl
as in #636 but for R21C
Contingent on https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/972
cc: @gmao-qliu @biljanaorescanin
> M21C: add definition of land constants collections into HISTORY_R21C.rc.tmpl

- construct_extdata_yaml_list.py
ExtData yaml file for DataAtm has been added to the extdata_yaml_list file.
> Adding DataAtm .yaml file to extdata_yaml_list

- gcm_forecast.tmpl
- gcm_run.j
- gcm_setup
This PR adds protections to v12 for TSE_TMPDIR namely:
* if it does not exist (NAS, etc.)
* or a user doesn't want to use it
> v12: Add protections for TSE_TMPDIR

- gcm_setup
- geoschemchem_setup
- gmichem_setup
- stratchem_setup
Skylakes are no more at NCCS, remove them.
We also make Romes the default at NAS.
> v12: Remove Skylake at NCCS

- gcm_setup
- geoschemchem_setup
- gmichem_setup
- stratchem_setup
This removes Skylake at NCCS. It also make Rome the default at NAS.
> v11: Remove Skylake at NCCS

- gcm_setup
- geoschemchem_setup
- gmichem_setup
- stratchem_setup
This PR removes the OS detection at NCCS. Not needed now that SLES15 is done.
> v12: Remove NCCS OS detection

- gcm_setup
- geoschemchem_setup
- gmichem_setup
- stratchem_setup
This PR removes NCCS OS detection.
> v11: Remove NCCS OS detection

- gcm_run.j
- gcm_setup
- geoschemchem_setup
- gmichem_setup
- stratchem_setup
The sed for `ice_in` in https://github.com/GEOS-ESM/GEOSgcm_App/pull/755 was a bit too lazy and was changing too much. This should fix it.
> v11: Fix sed for ice_in
