GEOS-ESM/GEOSgcm_App

gcm_setup
I did not understand how this really worked and @bmauer found out it was
working for @mathomp4 because @mathomp4 "fixed it".
In truth, the code was crushing installed files in `install/etc`. Now it
is a bit more careful by copying from `install/etc` and then doing all
manipulations in `install/bin`. Should probably be doing this in a
`mktemp` directory, but seems to work for now. At least, @bmauer could
run
=> Fix gcm_setup to not crush tmpl files

gcm_setup
`readlink` on macOS isn't like that on Linux. Use `realpath` if Darwin
=> Fixes #17. Allow macOS to run gcm_setup

gcm_run.j, gcm_setup
Turns out I'd never tested the ioserver `gcm_setup` code on the desktop (or, well, Parcel).
=> Fixes to allow dev/MAPL-2.0 to work on desktop

gcm_regress.j
This fixes the gcm_regress.j script when the cap_restart is before the magic date for merra2
=> Fix gcm_regress.j script

AGCM.rc.tmpl, gcm_setup
This PR selection of Ocean Model (MOM5 or MOM6) when running `gcm_setup`.
This adds a resource `OCEAN_NAME` in `AGCM.rc` that is only used in the `COUPLED` mode.
This is ongoing work related to issue GEOS-ESM/GEOSgcm_GridComp#70
Change-Id: If1c79e9204076c4e78b69fbe1b46d3952e212b8b
=> MOM6 in GEOS

scm_setup
This makes `scm_setup` be "better". The script now can be run from
anywhere and asks for `--expdir` and `--case` to make an experiment.
This is better than the old script where you had to run it from where
you want to run the experiment.
=> Fixes #47. Update scm_setup to be a better script

CMakeLists.txt, gcm_CPLFCST360NM2_setup, gcm_CPLFCST360S2S_setup, gcm_CPLFCST360S2Sallsetup, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
We removed the `gcm_stats.j` script from here, but the `*_setup` scripts are still looking for it. Not good.
=> Fixes #63. Remove references to gcm_stats in setup

AGCM.rc.tmpl
this is redundant now that we're using Icarus-NLv3 boundary conditions (both use lookup heights for vegetation based on Dorman & Sellers 1989). Worse, it'll cause confusion when in the future, we move to using LIDAR-based heights. When IGNORE_VEG_HEIGHTS was implemented, it was tested to be 0diff with what is now Icarus-NLv3  BC's
=> remove IGNORE_VEG_HEIGHTS

gcm_setup
Because of how the `gcm_setup` script works, if you add a new thing
going through `sed` you have to define it everywhere. So both NAS and
"else" now define a `REPLAY_ANA_EXPID` and `REPLAY_ANA_LOCATION`. But so
that no one thinks you can use it, we use a nice bold message. At NAS
only MERRA-2 replay is supported. Elsewhere, just plain unsupported.
=> Fix gcm_setup at non-NCCS locations

gcm_convert.j
Per @lltakacs, `gcm_convert.j` does not work. This seems due to changes
in how `gcm_setup` and `gcm_run.j` interact. This change seems to fix
it.
Note: the big `linkbcs` update might be overkill for this script but it worked and I don't want to figure out what lines aren't needed. :smile:
=> Fix gcm_convert.j

GCMPROG.rc.tmpl, HISTORY.AGCM.rc.tmpl, HISTORY.rc.tmpl, HISTORY_FP.rc.03z.tmpl, HISTORY_FP.rc.09z.tmpl, HISTORY_FP.rc.15z.tmpl, HISTORY_FP.rc.21z.tmpl, HISTORY_S2S.rc.tmpl, fvcore_layout.rc
Enhancements to GF and transport consistent with ops 525land_fpp. Must be taken in conjunction with pull requests in [GEOSgcm_GridComp#190](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/190), [GEOSchem_GridComp#47](https://github.com/GEOS-ESM/GEOSchem_GridComp/pull/47), and [GMAO_Shared#70](https://github.com/GEOS-ESM/GMAO_Shared/pull/70).
=> Add NISV to histories and default k_split value

gcm_CPLFCST360NM2_setup, gcm_CPLFCST360S2S_setup, gcm_CPLFCST360S2Sallsetup, gcm_archive.j, gcm_convert.j, gcm_emip.setup, gcm_forecast.tmpl, gcm_moveplot.j, gcm_plot.tmpl, gcm_post.j, gcm_regress.j, gcm_run.j, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
In case of SLES12 upgrade removing support for `#PBS` under SLURM 19, this commit *should* do all SBATCH at NCCS
=> Fixes #93. Remove #PBS pragmas at NCCS

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Fixes GEOS-ESM/MAPL#170.
I think we finally have this. These changes should let MAPL 2 GEOS work with MPT at NCCS. This:
```
unsetenv SUPPRESS_XPMEM_TRIM_THRESH
```
is a setting at NAS but not at NCCS and seems to help.
Note that this still isn't sufficient to allow MAPL 2 GEOS with MPT to work on SLES 12 Haswell. There are actual kernel changes needed to allow that, but NCCS is aware.
=> Update to let MAPL 2 GEOS work with MPT

gcm_CPLFCST360NM2_setup, gcm_CPLFCST360S2S_setup, gcm_CPLFCST360S2Sallsetup, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Testing by @bena-nasa and myself shows that at high core count (say, C720 at 5000+ cores) using Intel MPI on the Skylakes at NCCS needs an additional environment variable.
It turns out that the default [ALLREDUCE algorithm](https://software.intel.com/en-us/mpi-developer-reference-linux-i-mpi-adjust-family-environment-variables) Intel MPI chooses seems to be:
```
2. Rabenseifner's
```
*Any* other algorithm seems to work except for this one!
After some testing it was found algorithm 12:
```
12. Topology aware SHM-based Knary
```
seemed as good as any and might have been the fastest. If nothing else, it allows GEOS to run.
Testing at C48 has shown it to be zero-diff and no substantive throughput difference.
=> Fixes #111. Use different ALLREDUCE algorithm

gcm_CPLFCST360NM2_setup, gcm_CPLFCST360S2S_setup, gcm_CPLFCST360S2Sallsetup, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Using `I_MPI_ADJUST_GATHERV=3` seems to fix #118. Tests at c48 are zero-diff.
=> Fixes #118. Change Intel MPI GATHERV algorithm

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
My testing so far shows that this should allow one user to run `gcm_setup` in another user's `install/bin` directory.
That said, I've only really tested with `gcm_setup` but I've edited the other chem setups as well. Thus, it might be nice for @GEOS-ESM/chemistry-gatekeepers and @GEOS-ESM/geoschemchem-team to take a look and make sure I didn't screw up the GMI, SC, and GEOSChem scripts. I tried to be careful.
Also, this does get rid of the odd `HISTORY.rc.hold` mechanism. @lltakacs isn't sure anyone is actually using it. If it's needed I think I can see how to bring it back. (The ultimate test is to remove the capability and see if anyone complains. My guess? No one will.)
=> Fixes #120. Allows another user to run gcm_setup

gcm_CPLFCST360NM2_setup, gcm_CPLFCST360S2S_setup, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This adds a hidden `--link` option to symlink `GEOSgcm.x` rather than copy it (or, I guess `rsync` it). 
This is mainly for us @GEOS-ESM/gmao-si-team folks that tend to link `GEOSgcm.x` to our experiment so we can build-rebuild many times and not worry about re-copying it. If you never pass in `--link` you'll never see a difference.
=> Fixes #114. Add link option

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This commit adds a commented out `setenv` for running with MPT which can help in debugging when Intel's traceback is suppressed by MPT.
Commented out so that current behavior is maintained, but the flag is here for easy enabling
=> Fixes #123. Add commented FOR_IGNORE_EXCEPTIONS

geoschemchem_setup, gmichem_setup, stratchem_setup
Updated gmichem_setup, stratchem_setup and geoschemchem_setup, so that the resulting gcm_run.j script works with no edits required.  StratChem and GEOS-Chem are zero diff;  GMI experiments now explicitly set GMICHEM_DT, which is generally 2 * HeartBeat; in previous Git releases,  GMICHEM_DT defaulted to the HeartBeat.  Since gcm_setup has not changed, this PR is zero-diff.
=> Bring chem setup scripts better in line with gcm_setup

AGCM.rc.tmpl, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR updates a few things:
* For Intel MPI at NCCS, it sets a few settings that have proven useful by @wmputman and @sdrabenh 
* For Open MPI, it turns on `WRITE_RESTART_BY_OSERVER: YES` (the default `NO` is kept for all other MPI stacks). This is needed because there is some weird issue with Open MPI and GEOS where writing restarts at even, say, c90 can take hours without this. This needs a line added to `AGCM.rc.tmpl`
* Set `PARALLEL_READFORCING` to 0. This is from @atrayano who says this should be the default period. No matter what.
* Fix some spelling issues I saw when reading `AGCM.rc.tmpl`
* Add in `c12` and `c24` to the "what resolution" print of the `_setup` scripts. I know of a few people I've told to try c24 and then they are confused since it's a "hidden" option.
=> Update MPI Settings

AGCM.rc.tmpl
This is in combination with https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/312 to allow the new NCAR GWD to pass stop-start regression. We need `DTDTCN` to be saved so GWD can restart correctly.
Note I'm labeling this both 0-diff and non-0-diff as it is zero-diff in the sense that the results are the same, but non-zero-diff in that new restart appears.
@sdrabenh can remove a label as he sees fit :)
=> Add gwd_import to checkpoint/restart

gcm_convert.j, gcm_forecast.tmpl, gcm_regress.j, gcm_run.j
Under CMake, `binarytile.x` isn't compiled with MPI. For unknown reasons, Intel MPI 19.1.2 sometimes has issues running it with `mpirun`. It shouldn't, but...
Still, as it isn't even compiled with MPI, there is no need to run with MPI.
=> Do not run binarytile.x with MPI

AGCM.rc.tmpl
Removes hardcoded BERES_FILE_NAME and makes it an ExtData file from AGCM.rc
Should be taken in concert with https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/341
=> Genericize NCAR GWD Beres file location

gcm_run.j
Split saltwater restart: bug fix for running emip and correct exit status
=> San akel patch 2

logging.yaml
Trivial change to configuration, but with desirable results.
Other:
- introduced new "legacy" format for those that do not want the
message annotations.
- also a bit of cleanup
=> Fixes #167 - duplicated pflogger messages

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This should increase the job name limit that is in the `_setup` scripts. Back in ye olde days, PBS could only handle 16 character. Now SLURM can handle 1024 and PBS at NAS can do 230. This update puts the limit at 200...which is good for almost anything!
=> Fixes #164. Increase job name limit

CMakeLists.txt
When a `GLOB` is used in CMake, the CMake system doesn't check to see if files in the `GLOB` change when re-running `cmake`. Thus if someone adds/removes a file that the `GLOB` would pick up, say, CMake might not see there is a change and things go a bit pear-shaped. But there is [a `CONFIGURE_DEPENDS` flag](https://cmake.org/cmake/help/latest/command/file.html#glob):
> If the CONFIGURE_DEPENDS flag is specified, CMake will add logic to the main build system check target to rerun the flagged GLOB commands at build time. If any of the outputs change, CMake will regenerate the build system.
While CMake prefers no `GLOB` at all (as `CONFIGURE_DEPENDS` isn't supported for all generators), for now this is a possible partial solution until the CMake could be rewritten to explicitly list all …
=> Use CONFIGURE_DEPENDS with GLOB

gcm_run.j, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This is an update to the PBS stdout/stderr handling at NAS. To wit, before, if run under batch, a job would produce three files:
```
stock-gcm-2021Jan19-1day-c24-BATCH_RUN.e10442444
stock-gcm-2021Jan19-1day-c24-BATCH_RUN.o10442444
gcm_run.10442444.pbspl1.nas.nasa.gov.20000414.out
```
The first two were the bits of stderr and stdout from PBS but the third was the direct output from GEOS. This made NAS unlike NCCS where SLURM puts all our output in the `slurm-42018658.out` file, say. This was done because the only way to monitor a job at NAS was to go to the head node of the compute allocation and tail the files in `/PBS/spool`
With this PR, we join stderr and stdout `-j oe`, and then use `-k oed` to now produce one file:
```
updatePBS-gcm-2021Jan19-1day-c24-BATCH_RUN.o10442667
```
that is …
=> Fixes #194. Update the PBS Batch handling at NAS

gcm_run.j
This is zero diff.
The new file (listed in comments) has been used in pre-industrial climate simulations, and includes extra production and loss fields; code to use those fields has been added to the repo GEOSchem_GridComp (develop branch) PR # 112 , and the new species file serves as an example of what's needed.
=> Added optional PCHEM species file with prod/loss of strat water vapor

AGCM.rc.tmpl, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
We have the MERRA-2 replay files at NAS, but the location in `AGCM.rc.tmpl` is hardcoded for Discover. With this PR, it should now be automatically set on both NCCS and NAS.
=> Support "automatic" MERRA-2 Regular Replay at NAS

gcm_regress.j, gcm_run.j, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
As part of the DSO work by @weiyuan-jiang, the `OCEAN_PRELOAD` business is no longer needed. So, this PR removes `OCEAN_PRELOAD`. 
Note that this is contingent on updates to FMS (https://github.com/GEOS-ESM/GEOSgcm/pull/254), MAPL (https://github.com/GEOS-ESM/MAPL/pull/701) and GEOSgcm_GridComp (https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377) being accepted. So I've added the blocker to this.
=> Remove OCEAN_PRELOAD

gcm_regress.j
Fixes `item 2` of:
https://github.com/GEOS-ESM/GEOSgcm_App/issues/205
By adding `MOM.res.nc` to the list of restarts that are checked in regression testing.
@sdrabenh: please note this branch is based off `feature/wjiang/mom_dso`(https://github.com/GEOS-ESM/GEOSgcm_App/tree/feature/wjiang/mom_dso) which fixes `item 1`(https://github.com/GEOS-ESM/GEOSgcm_App/issues/205): `LD_PRELOAD`. That's the reason for this **contingency** 🧬
=> Bugfix/san akel/regr include mom rst

gcm_setup
Per @lltakacs, we are missing an update to gcm_setup for the GAAS ana aod replay files. This change is in CVS (say, `GEOSadas-5_27_1_p3`) but got missed on the way to Git.
It's zero-diff trivially for an AMIP, but if this isn't quite right, GAAS might not work as expected...
=> Update GAAS Replay fix

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Rome processors at NAS needs an extra aoe in PBS.
Also, the Rome IO issues are...omnipresent, so let's not blame IOSERVER
=> Fixes #210. Updates for (hidden) Rome at NAS

CMakeLists.txt, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR will change setup scripts depending on what `-DHYDROSTATIC` option was supplied to CMake. So if you provide `-DHYDROSTATIC=ON` then it will assume you want to use hydrostatic dynamics options and vice versa.
Note: This requires fvdycore v1.1.5 (see https://github.com/GEOS-ESM/GEOSgcm/pull/273)
=> Change setup scripts depending on HYDROSTATIC build

logging.yaml
In https://github.com/GEOS-ESM/MAPL/pull/801 I've added some debug pFlogger messages for the NRL Sun code. While this doesn't hurt anything, the default level of logging for MAPL is currently `DEBUG` on root. So, once https://github.com/GEOS-ESM/MAPL/pull/801 goes in, the NRL sun code will get noisy in logging, e.g.,:
```
0000: MAPL.SUN: DEBUG: Off the end of table, moving into last complete cycle
0000: MAPL.SUN: DEBUG:   Original Year-Mon-Day to Find: 2021-02-15
0000: MAPL.SUN: DEBUG:   Original Day of Year: 46
0000: MAPL.SUN: DEBUG:   New Year-Mon-Day to Find: 2010-02-16
0000: MAPL.SUN: DEBUG:   New Day of Year: 47
0000: MAPL.SUN: DEBUG:   First DOY to Find:      47
0000: MAPL.SUN: DEBUG:     file_index for date:  46798
0000: MAPL.SUN: DEBUG:     yearTable(date):     2010
0000: …
```
=> Update MAPL logger

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This is a hotfix to allow GEOS to run the Old Land BCs. The fix was:
1. Missing comma in the `LAND_PARAMS:` awk command
2. `Z0_FORMULATION:` also must change (from 4 to 2) when running the Old Land.
With both these fixes, my tests show zero-diff for running against the old land before GEOSgcm_App v1.5.0 was in.
=> Fix for running Old Land BCs

gcm_run.j
We know on the Romes that using the MAPL IOSERVER "out of the box" doesn't quite work well. Probably has to do with the number of cores on the Rome being stupid high and...doing things wrong? Dunno.
But, working with @weiyuan-jiang, it was found that the Romes work better if we use the MultiGroup server version of IOSERVER. So this PR tries to "automate" what @weiyuan-jiang said is the best way to set up the MultiGroup server. To wit, he says the best number of backend PEs is the number of history collections divided by the number of ioserver nodes.
This change tries to do that. First, using some `sed` we try to calculate the number of history collections active. I tried my best but I'm guessing somewhere out there is a HISTORY.rc that will break this, but it works with the …
=> Fixes for IOSERVER on Rome

AGCM.rc.tmpl
This PR changed the component name specification in `AGCM.rc.tmpl` for `CICEDyna` grid comp from `SEAICE` to `CICE4`. It is required by the newly introduced `GEOS_SeaIceGridComp`.
It is continent on https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/424
=> changed the component name specification for CICEDyna

gcm_convert.j, gcm_forecast.tmpl, gcm_run.j, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Per a discussion between @sdrabenh and myself, it seems "right" that if you select OPS emissions in `gcm_setup`, you should also use the OPS species file (prod/loss). If not, sometimes you get the "MERRA2OX Crash" a la #218 and #233 .
What this PR does is try and say:
- If you choose OPS emissions, use the OPS prod/loss species, `pchem_clim_years: 1`
- If you choose CMIP emissions, use the CMIP species, `pchem_clim_years: 228`
- ELSE, use the MERRA2OX species (aka the default behavior from before), `pchem_clim_years: 39`
Now, I think I got this right for `gcm_setup` and I *tried* to get it right in the other setups, but `gmichem_setup` is fancy. As such, I now ping @mmanyin to see if he thinks I got it correct. (The `stratchem_setup` and `geoschemchem_setup` seemed pretty easy to change …
=> Make species consistent with emissions choice

CMakeLists.txt, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Closes #234 
This is a bit of safety for running at NAS. Namely, if a user builds on the Rome processors at NAS, they build for Romes using slightly different optimization as well as on an entirely different OS (SLES 15). Now it's possible you could use a built-for-Rome executable on the Intel chips (if they were SLES 15) but the answers would be different so, this is a double-protection. (The latter restriction might be lifted when all of NAS is on SLES 15? Though not sure. Needs to be tested.)
But, for now, if you build on Romes, you can *only* run on Romes with this. To run on other cores, build on an Intel.
=> Only allow Rome nodes at NAS if built on Rome

gcm_run.j, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
These are updates from recent testing with MVAPICH2.
Note part of this is trivial (the MVAPICH2 bits) but it also enables the multigroup oserver by default if using IOSERVER nodes. This is based on conversations with @weiyuan-jiang. We don't affirm that this is an *ideal* setup (number of IONODES, etc), but it at least gets people closer to a better setup automatically.
Should be taken in concert with https://github.com/GEOS-ESM/GMAO_Shared/pull/198 (but not *required*, just should)
=> Updates for MVAPICH2, Enable multigroup by default

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR fixes a missed path from #233. Forgot to test GOCART.data. As `PCHEM_CLIM_YEARS` was never set in that path, GOCART.data experiments could not be made.
In order to keep things "the same" with GOCART.data, we set the "default" `PCHEM_CLIM_YEARS` to 39 as before GOCART.data was using the 39-year MERRA2OX species file.
=> Fix for GOCART.data

CMakeLists.txt, gcm_convert.j, gcm_forecast.tmpl, gcm_regress.j, gcm_run.j
@tclune requested some changes to comments on a PR syncing the CTM to GEOSgcm v10.19.3 (https://github.com/GEOS-ESM/GEOSctm/pull/34).
This PR pulls those changes back into the GCM so we can keep both in sync. (Not often we go CTM → GCM!)
=> Update comments in line with CTM

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Recently, my GEOS regression runs at NAS have had momentary "cannot launch MPT" issues. NAS has a [help page](https://www.nas.nasa.gov/hecc/support/kb/mpt-startup-failures-workarounds_526.html) about this and one of the suggestions is to add `MPI_LAUNCH_TIMEOUT=40`. So, this PR adds that as a new variable if using MPT.
I'm going to look at adding the file system mounts as well, but that can't really be put in `gcm_setup`, et al., so it'll be in my nightly scripting scripts.
As for `several_tries`, it seems overkill for now for all GEOS runs, but if I get complaints I'll look at adding it as well (maybe by default at high-res??)
=> Add MPI_LAUNCH_TIMEOUT for MPT

CMakeLists.txt
This is just cosmetic. We know how to do OpenMP in CMake better now, so we should!
=> Clean up OpenMP in CMake

CMakeLists.txt, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Adds a hidden option for Cascade Lake cores at NCCS. This will at least let people with access get good IOSERVER, etc. setups.
NOTE: Cascade Lake requires Intel 2021.2 or later. I'll probably recommend 2021.3 as that's available at NAS too...but it's also a non-zero-diff compiler. 😞
=> Updates for Cascade Lake at NCCS

gcm_run.j
When running cnclm40, remove CNFROOTC from history. But it is users' responsibility to put it back when switch to cnclm45 again
=> remove CNFROOTC when running CNCLM40

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
NCCS is recommending not to run on all 48 cores of the Cascade Lake nodes in SCU16. They recommend CPU intensive codes use 46 or less cores. We choose 45 as that is at least a multiple of 3 so with an even number of nodes, we can get good divisible-by-6 whole nodes.
=> Use 45 cores per node with SCU16 per NCCS

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This fixes a dumb bug found by @AgilentGCMS . Namely, if you try to run `install/bin/gcm_setup` from anywhere *but* `install/bin` it fails. And with a weirdly dumb message:
```console
$ cd ~
$ /discover/swdev/mathomp4/Models/GEOSgcm-RegridUpdate/GEOSgcm/install-Release/bin/gcm_setup
You are trying to run /discover/swdev/mathomp4/Models/GEOSgcm-RegridUpdate/GEOSgcm/install-Release/bin/gcm_setup in the Applications/GEOSgcm_App directory
This is no longer supported. Please run from the bin/ directory
in your installation
```
The intent was to make sure people didn't run the `gcm_setup` in the `src/Applications/GEOSgcm_App` directory, but it doesn't mean you can't run the "real" `gcm_setup` from other directories as long as you give the right path.
=> Fix for setup scripts

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
In testing with MPICH, it was found that since MPICH isn't known by `gcm_setup`, it defaults to Intel MPI. And one of the Intel MPI environment variables seem to cause a crash with MPICH!
So, this PR adds MPICH to the list of known MPI stacks. Note that nothing actually happens "if mpich" yet, so this is just a way to short circuit the Intel MPI default.
=> Add mpich to list of MPI stacks

CMakeLists.txt, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Now that NAS defaults to TOSS nodes, we can fix up the `gcm_setup`, et al, scripts to be more generic.
NOTE: Keeping this as Draft until NAS moves the head nodes to TOSS. Right now NAS is a bit twitchy during the transition.
=> Update NAS nodes for TOSS

gcm_convert.j, gcm_forecast.tmpl, gcm_regress.j, gcm_run.j, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR combines:
- https://github.com/GEOS-ESM/GEOSgcm_App/pull/285
- https://github.com/GEOS-ESM/GEOSgcm_App/pull/287
- https://github.com/GEOS-ESM/GEOSgcm_App/pull/291
into one PR. I was doing some testing and found some fun Git merge conflicts that @sdrabenh doesn't need to deal with. So I do it for him. 
This has been tested at NAS and it runs C12-NewLand-MOM6 and C90-OldLand-MOM6
More info below:
---
This PR updates the setup scripts in many ways. It includes:
- Fixes some csh logic for making the tile names
- Remove `setenv I_MPI_DAPL_UD enable`. Intel MPI doesn't even recognize this flag anymore:
```
I_MPI_DAPL_UD variable has been removed from the product, its value is ignored
```
- Remove the ROMIO environment variable for Intel MPI
- Default C12 MOM6 as 1x6 atmos/3x2 ocean. …
=> Omnibus Ocean and NAS Updates to setup

AGCM.rc.tmpl
fvsetup sets the parameter LDAS_INCR to default 0 , user input can set it to 1 for land-atmos coupled das experiment.
=>         add LDAS_INCR to AGCM.rc.tmpl for land-atmos coupled das

AGCM.rc.tmpl
This update from @dr0cloud updates RRTMGP files. Note that these are commented out by default and even then, won't be read by the GCM unless RRTMGP is enables.
This is trivially zero-diff.
=> Update RRTMGP file locations and half gpoints

CMakeLists.txt
Due to insufficient grepping on my part, some remnants of the
"not-canonical" CMake still remain. Apparently these were not necessary
changes for Spack, but they are changes that unify the CMake style of
GEOS to be more like "correct" CMake.
In this go-around, it is mainly finding `INC_ESMF` which I apparently
forgot to grep for last time (I was focused on NetCDF).
=> Updates for Spack Support, Round 2

gcm_forecast.tmpl, gcm_regress.j, gcm_run.j
Thanks to @mmanyin, it was found that #320 wasn't quite the full fix. The issue was the run scripts were still doing links to `$EXPDIR/RC` instead of full copies. Thus, the symlinks that were in `$EXPDIR/RC` were mutable and then the run script could screw them up after the fact.
Instead, we *copy* RC files from `$EXPDIR/RC` and then all is well. The AMIP changes cannot propagate back to `$EXPDIR/RC`
=> Fix Emissions Handling: Use copy not link

AGCM.rc.tmpl
Added internal and import restart files for OH, which will be introduced under the QuickChem module in the upcoming CHEMISTRY release.  This is zero diff.
=> Add OH restart files (commented out)

gcm_convert.j, gcm_regress.j, gcm_run.j, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Recent testing with mom5 by @yvikhlya and @sanAkel (see https://github.com/GEOS-ESM/GEOSgcm/issues/352 and https://github.com/GEOS-ESM/GEOSgcm/issues/430) in GEOSgcm has shown a need to bring back the old `LD_PRELOAD` mechanism that was removed in #204. So this PR brings back `LD_PRELOAD` but only in the case of MOM5
Obviously not ideal, but until this oddity can be examined by @tclune and @weiyuan-jiang (and maybe @atrayano), ~we bring back `LD_PRELOAD` *ONLY* when running MOM5 as runs of MOM6 don't seem to care!~
As @yvikhlya pointed out below, MOM6 might only work due to luck. So we preload both.
=> Add LD_PRELOAD for Coupled Model

.circleci/config.yml
This PR adds CircleCI tests to GEOSgcm_App. PRs will both build the model (nigh trivial since only `GEOSgcm.F90` is here, but it could catch CMake issues) and then *run* the model for 1 hour (this might catch History issues?).
Still, we've gone too long without it here.
=> Add circleci tests to GEOSgcm_App

construct_extdata_yaml_list.py
I created an ExtData yaml file for GEOS-Chem, which is now included in the `geos/develop` branch of geos-chem ([GEOSCHEMchem_ExtData.yaml](https://github.com/GEOS-ESM/geos-chem/blob/geos/develop/run/GEOS/GEOSCHEMchem_ExtData.yaml)). This PR simply ensures that this yaml file gets indeed read when using EXTDATA2G.
=> Add GEOSCHEMchem_ExtData.yaml to list of yaml files for EXTDATA2G

gmichem_setup, stratchem_setup
This PR is zero diff for everything except GMI and StratChem setup scripts.
GMI: removed old rc files for CCMI REF-C1, C2
StratChem: SC and TR species are no longer in Chem_Registry.rc; also we now account for AMIP copies of files
=> Update gmichem_setup, stratchem_setup

gcm_run.j
... for tripolar collections in previous PR and this PR removes linking tile_hist.data in gcm_run.j script, since it is not necessary anymore. Interpolation of tripolar output to latlon grid is done with `grid_label` option. Perhaps, `regrid_exch` option should be removed from MAPL too, but I am not sure about this.
=> Bugfix/yury/aogcm notilehist `regrid_exch: tile_hist.data` was removed from history template

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
As discovered by @wmputman, L181 runs were failing with ExtData2G. Until a proper fix can go into MAPL, etc. this is a quick fix to let things work. 
@bena-nasa has tested and it works for him.
Note to @sdrabenh: You'll want to do the same thing in the Bill development branch as well.
=> Fixes for non-72-level runs with ExtData2G

.github/workflows/validate_yaml_files.yml, .yamllint.yml, logging.yaml
This PR is a minor update to the `logging.yaml` file which will be useful for an upcoming MAPL PR:
https://github.com/GEOS-ESM/MAPL/pull/1938
Without the MAPL PR, no change should be seen in log output. This PR in combination with the MAPL PR will change:
```
MAPL: INFO: Model Throughput:     1001.424 days per day
```
to:
```
Model Throughput:     1001.203 days per day
```
I've also added the GEOS YAML validator action as well. Always nice make sure our YAML is good.
=> Update logging.yaml, add YAML linter

gcm_forecast.tmpl, gcm_run.j, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Testing on AWS exposed a bug in the calculations used for oserver use in the setup and run scripts. The issue is this code:
```csh
set NUM_MODEL_NODES=`echo "scale=1;($MODEL_NPES / $NCPUS_PER_NODE)"  \
| bc | awk 'function ceil(x, y){y=int(x); return(x>y?y+1:y)} {print ceil($1)}'`
```
and the `scale=1` bit. 
What this is supposed to do is divide the model NPES by the NCPUS_PER_NODE and then round *UP* with that `ceil()` function in case of a partial node.
And it does that. 
90% of the time.
On AWS, we were running 15x60 = 900 model PEs and 64 cores per node. By hand we see this is 14.0625 nodes → round up to 15.
Now the math:
```shell
❯ echo "scale=1;900./64." | bc
14.0
❯ echo "scale=1;900./64." | bc | awk 'function ceil(x, y){y=int(x); return(x>y?y+1:y)} {print ceil($1)}'
14
```
Oh dear. …
=> Fix issue with oserver node calculations

gcm_setup
Because you can only run on Romes at NAS if you build on Romes at NAS (because of different OSs), this PR is an attempt to allow users to only select Rome nodes if you built on Rome, and only Intel nodes if you built on Intel.
Note that this requires an update to ESMA_cmake:
https://github.com/GEOS-ESM/GEOSgcm/pull/531
so I'm blocking here until that gets pulled into GEOS first.
ETA: It was pulled in, so I'm undrafting!
=> Allow only Rome builds to run on Romes at NAS

geoschemchem_setup, gmichem_setup, stratchem_setup
Mea culpa. With PR #411 I only touched `gcm_setup` and I forgot to update the stratchem, GMI, and GEOS-Chem scripts.
For @mmanyin and @christophkeller 's benefit:
Because you can only run on Romes at NAS if you build on Romes at NAS (because of different OSs), this PR is an attempt to allow users to only select Rome nodes if you built on Rome, and only Intel nodes if you built on Intel.
=> Add Rome detections to other setup scripts

gcm_regress.j
This PR changes up the `gcm_regress.j` script to now do:
1. Run 24 hours at NX x NY
2. Move back to orig restarts, run 6 hours at NX x NY
3. Run 18 hours at NX x NY
4. Move back to orig restarts, run 6 hours at 1 x 6
So, comparing the output of 1 and 3 look at start-stop regression and 2 and 4 look at layout regression.
=> Separate out the two regression tests: start-stop and layout

logging.yaml
This PR updates the `logging.yaml` file with a nice example based on the one found on the [MAPL wiki for logger](https://github.com/GEOS-ESM/MAPL/wiki/How-to-use-the-MAPL-logging-library,-aka-%22pFlogger%22).
Also, some of the "example" commented out loggers in the file are fixed up for GOCART2G.
Finally, some indentation is made consistent with the 3-space indents throughout the file.
=> Update logging.yaml with example, some changes

AGCM.rc.tmpl, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR does a couple things.
First, it "borrows" the `>>>HIST_GOCART<<<` bit to delete lines in `AGCM.rc.tmpl` that removes the MCHEMTRI stuff from @atrayano and @bena-nasa when running GOCART Data. If those are enabled, crashes appear!
Second, I *tried* to update the other setup scripts with the changes from @wmputman in re DT change. My hope is that it all works but is just out of tune? Not sure. But probably @mmanyin will need to make tweaks. Sorry about that.
=> Update GOCART Data handling, update other setup scripts

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
With the whole TOSS4 transition at NAS, my nightly tests stopped running a while back. As such, I missed that we broke MOM6 at NAS. So, this PR fixes it by correcting a path.
NOTE: This is obviously zero-diff in the sense that it doesn't affect the AMIP runs and, well, without it, MOM6 can't even run at NAS!
=> Fix COUPLEDIR at NAS

HISTORY.AGCM.rc.tmpl, HISTORY.rc.tmpl, HISTORY_FP.rc.03z.tmpl, HISTORY_FP.rc.09z.tmpl, HISTORY_FP.rc.15z.tmpl, HISTORY_FP.rc.21z.tmpl
PM25 and PM diags were added to the inst2d_hwl and tavg3_aer collections and NH4SMASS was added to the inst2d_hwl collection in the HISTORY.rc files for FP, HISTORY.rc.tmpl, and HISTORY.AGCM.rc.tmpl.
=> Add PM fields to HISTORY

gcm_regress.j
Testing of `gcm_regress.j` at 137-levels showed we need to include the `gwd_internal_rst` copies that are in `gcm_run.j` also in the regress script.
Keeping draft until I can see if this is all that's needed.
=> Add gwd_internal_rst to gcm_regress.j

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
In talking with @christophkeller I realized I don't have a good test of even our lowest resolution stretched grid case, c270. So, in my testing, I found a couple of issues that need fixing.
1. Most of our BCs seem to assume we'd use a 4-digit resolution like `CF0720x6C`. But the low stretched cases had `CF270x6C` and not `CF0270x6C`. This sort of...broke some assumptions in my scripts. So we make it consistent.
2. It turns out the sed we have isn't perfect. The script has both `STRETCH_FACTOR` and `STRETCH_FAC`. For C270 these are `2.5` and `stretch_fac = 2.5`. But when sed did its thing, `AGCM.rc` ended up with:
`AGCM.STRETCH_FACTOR: stretch_fac = 2.5TOR`
which MAPL was *NOT* happy with. So we fix that.
=> Fixes for stretched grid

scm_run.j, scm_setup
The updates in v11 require fixes to sedfiles in the scminfiles. This PR brings them in.
NOTE: This PR in in combination with https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/725 The SCM will not run without that.
ETA: Per @narnold1, this only lets things work at L72. I have an idea on how to fix L137, but probably need the expertise of @bena-nasa to test. For now I'll keep this still mergable as it at least fixes part of the SCM.
=> Update to new SCM file dir

gcm_forecast.tmpl, gcm_run.j, gcm_run_benchmark.j
Addressing issue #471.  
This PR is using CO2 file needed for CatchCN offline simulations from boundary conditions area. 
To accommodate for this in "legacy_bcs" area we added this file to these boundary conditions versions. 
`Icarus-NLv3;
Icarus ;
Ganymed-4_0`
@gmao-jkolassa do you need me to add this to any other boundary conditions version? 
I will add one more PR to GEOSldas to change path for ldas_setup as well.
=> Moving catchcn CO2 file to bcs dir

gcm_run.j, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
NOTE: This is zero-diff for AMIP, but non-zero-diff for MOM6 due to changes to DT.
Per @amolod, until other fixes can go in (cc @atrayano), coupled runs must have `OGCM_RUN_DT` equal to the heartbeat. 
Moreover, I assume (?) that the `DT` and `DT_THERM` in `MOM_override` must have the same number. So I do some sed at the end of `gcm_setup` to change that as well. (@sanAkel or @yvikhlya can tell me if this is true.)
I don't know how to run MOM5 so I'm not sure if something similar needs to be done there with its input files. If someone can tell me what to look for, I can try to sed/awk that too.
I'll keep this draft until the coupled folks can weigh in on it. It seems to work for me...but they are the arbiters.
=> Coupled ocean DT must be heartbeat (for now)

gcm_run.j, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR has a change needed for singularity testing. Namely, a docker or singularity image might be built on the cloud in AWS or Azure and so the model thinks "I was built on AWS, I need to run on AWS" but this is not the case.
=> Updates for Singularity: Add site option

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Closes #491 
This PR fixes an issue with the cloning bits of `gcm_setup` et al. 
@dbarahon @Dooruk Can you try this branch out and see if it works for you?
=> Fixes #491. Fix for cloning in setup scripts

gcm_forecast.tmpl, gcm_regress.j, gcm_run_benchmark.j
In #508 I was dumb and didn't do the `MP_NO_USE_WSUB` → `MP_TURN_OFF_WSUB_EXTDATA` substitution in all the scripts. As such, the regress script broke. 
I *know* I tested this, so that means somewhere there is an un-pushed commit just hanging around. Sigh.
Mea culpa!
=> Fix WSUB use in other scripts

logging.yaml
In #508, I thought I was being clever. But it turns out I don't know pflogger that well. My entry for `CAP.EXTDATA` actually *doubled* all ExtData output:
```
EXTDATA: INFO: *******************************************************
EXTDATA: INFO: *******************************************************
EXTDATA: INFO: ** Variables to be provided by the ExtData Component **
EXTDATA: INFO: ** Variables to be provided by the ExtData Component **
EXTDATA: INFO: *******************************************************
EXTDATA: INFO: *******************************************************
EXTDATA: INFO: ---- 00001: BC_AIRCRAFT
EXTDATA: INFO: ---- 00001: BC_AIRCRAFT
EXTDATA: INFO: ---- 00002: BC_ANTEBC1
EXTDATA: INFO: ---- 00002: BC_ANTEBC1
EXTDATA: INFO: ---- 00003: BC_ANTEBC2
EXTDATA: INFO: ---- …
```
=> Fix doubled logger output

AGCM.rc.tmpl, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Per a comment by @wmputman:
> Anytime we run NH, we should enable FV3_CONFIG: HWT (this is a gcm_setup issue)
This PR does that. Per the starting code, we also enable `FV3_CONFIG: HWT` when running CONUS.
I'll mark as zero-diff as it is for hydrostatic runs, but it's also non-zero-diff (I assume) for NH runs. So...
=> Enable FV3_CONFIG: HWT for NH runs, CONVPAR_OPTION: NONE for ultra-high-res

gcm_setup
In testing @sdrabenh found an issue with running 4DIAU Replay with GEOS. @bena-nasa is looking at a fix in MAPL to make this moot, but if you have `WRITE_RESTART_BY_OSERVER: YES` and you run this flavor of replay, things will crash.
This is a temp fix to disable this flag at low resolution so that @sdrabenh can do testing more easily. Once there is a MAPL fix, we can undo this.
=> Turn off WRITE_RESTART_BY_OSERVER at low res Open MPI

gcm_setup
With the release of [MAPL 2.42.0](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.42.0) we can now undo the changes from #530.
=> Turn back on WRITE_RESTART_BY_OSERVER at all res

fvcore_layout.rc
This PR adds a new fv namelist entry for the AIST work by @tclune. To be used first https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/pull/83 → [GFDL_atmos_cubed_sphere geos/v2.7.0](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/releases/tag/geos%2Fv2.7.0) must be used.
There is a corresponding PR in FV3 (https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/pull/258) for the FV3 Standalone
By default, we add the flag as `.false.` which is zero-diff to current behavior. Enabling it will be non-zero-diff.
---
ETA: Now that [GFDL_atmos_cubed_sphere geos/v2.7.0](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/releases/tag/geos%2Fv2.7.0) is out and in GEOSgcm `main` (https://github.com/GEOS-ESM/GEOSgcm/pull/696), this can go in.
=> Add fv namelist entry for AIST work

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Per @sanAkel, MOM6 has "fixed" layouts per [this table](https://github.com/GEOS-ESM/GEOSgcm/wiki/Coupled-model-configurations-(GEOS-MOM6)). This PR hardcodes that info into the setup scripts to allow only those setups.
=> Use specific MOM6 Resolutions

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Nightly tests of GEOSgcm show that MAPL `develop` doesn't run at NAS under MPT (see https://github.com/GEOS-ESM/MAPL/issues/2515). This fixes that issue. 
Tests show that it doesn't affect MAPL 2.43 and below as well and it runs from C24 to C720.
=> Update MPT flags for use with MAPL 2.44 (current develop)

.circleci/config.yml
This PR updates the CircleCI orb to use the v2 orb. This is needed by both #552 and #544 so we might as well just get it on develop!
=> Update circleci-tools orb to v2

gcm_run.j
This commit introduces a logical variable 'wavewatch'. Said flag controls the handling of WAVEWATCH namelists and restarts in the gcm_run.j script.
=> Improve readability

AGCM.rc.tmpl, gcm_run.j
As noted by @sdrabenh, @sanAkel, and myself, recent runs of GEOS output:
```
cp: ww3_multi.nml: No such file or directory
ww3_multi.nml.orig: No such file or directory.
grep: ww3_multi.nml: No such file or directory
mv: rename ww3_multi.nml to ww3_multi.nml.tmp: No such file or directory
cat: ww3_multi.nml.tmp: No such file or directory
rm: ww3_multi.nml.tmp: No such file or directory
```
on runs.
Testing shows, it's because in this code:
https://github.com/GEOS-ESM/GEOSgcm_App/blob/b96f3e63002f9a7aec6e2755508f52617642e8a8/gcm_run.j#L632-L633
https://github.com/GEOS-ESM/GEOSgcm_App/blob/b96f3e63002f9a7aec6e2755508f52617642e8a8/gcm_run.j#L842-L845
`USE_WAVES` is not set to anything, but `wavemodel` is set to `WW3` (via `WGCM.rc`). And it seems an empty variable is not "falsey" like 0 in …
=> Initialize USE_WAVES to 0

gcm_regress.j
Closes #571 
Closes #572 
This PR moves `gcm_regress.j` to use `nccmp` instead of `cmp` for comparison of restarts (non-MOM).
It also changes `NUM_READERS` and `NUM_WRITERS` to 6 for the 1x6 layout test as a test of that.
NOTE: We move to use `nccmp` as it was found that there seem to be differences in the HDF5 Superblock when written with multiple writers. The data and metadata is all the same, but something changes and then, boom, different files *technically* such that `cmp` will not work.
=> Use nccmp, add readers/writers test to regress

AGCM.rc.tmpl, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR disables the option for using the Catchment-CN4.5 land model (LSM_CHOICE=3) in GCM simulations. The PR also fixes a minor typo that was present in the error message displayed for invalid values of LSM_CHOICE.
This PR is zero-diff.
Related PRs:
https://github.com/GEOS-ESM/GEOSldas/pull/707
https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/900
cc: @gmao-rreichle , @biljanaorescanin
=> Disable Catchment-CN4.5 land model option (LSM_CHOICE=3) for GCM simulations

HISTORY.rc.tmpl
Add specs for land surface forcing (lfo) collection from the **predictor** segment to HISTORY.rc.tmpl.  This is needed for weakly-coupled land-atmosphere assimilation.
=> add surface forcing  lfo_Nx+-   to HISTORY.rc.tmpl  

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR uses CMake to determine the MPI stack rather than looking at the content of `$BASEDIR` which builds that use Spack will never fill. 
NOTE 1: This requires ESMA_cmake v3.41.0 which is now in GEOSgcm (see https://github.com/GEOS-ESM/GEOSgcm/pull/752)
NOTE 2: There is still a *lot* of `BASEDIR` hanging around, but this is at least a first step.
=> Use CMake to determine MPI Stack

HISTORY_FP.rc.03z.tmpl, HISTORY_FP.rc.09z.tmpl, HISTORY_FP.rc.15z.tmpl, HISTORY_FP.rc.21z.tmpl
this follows discussion w/ Allie and others about OpenDap missing output from forecasts.
This is aimed at the branch GEOS-FP.
Matt: could you please protect this branch.
Scott: I would like this to be tagged as follows:  v1.5.6.3-GEOS-FP-1  - since this is a v-tag; I am not sure I can myself tag it. Perhaps Matt can tell me.
=> Patch FP: add missing nitrate output

gmichem_setup, stratchem_setup
Comment out a reference to PCHEM::OX MOIST tendency, in AGCM.rc, when setting up a GMI or StratChem experiment.
(When the tendency term is present, and PCHEM is not running, the model crashes.)
Currently GMI and StratChem do not use the scavenging functionality of MOIST.
If GMI uses it in the future, we will change the reference PCHEM::OX to GMICHEM::OX .
=> Minor update to GMI and StratChem setup scripts

gcm_archive.j, gcm_forecast.tmpl, gcm_moveplot.j, gcm_plot.tmpl, gcm_post.j, gcm_quickstat.j, gcm_regress.j, gcm_run.j, gcm_run_benchmark.j, scm_run.j
In testing building and running GEOSgcm with Spack as libraries instead of Baselibs, it was found that you can't do things like:
```
setenv @LD_LIBRARY_PATH_CMD ${LD_LIBRARY_PATH}:${BASEDIR}/${ARCH}/lib:${GEOSDIR}/lib
```
if `BASEDIR` is not defined.
So, we only add `BASEDIR` if it is defined in the environment.
=> Updates for non-Baselibs runs

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
In doing some testing of the stretched grid, I found that the tags set by the setup scripts weren't quite right. Turns out it was fairly simple to fix up once I figured out where to look.
=> Fix up stretched grid tags

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR updates NX, NY, and various DT per calculations by @wmputman
We also move to use even division on nodes at NCCS at NAS. This means 24, 40, and 120 cores per node on the various node types.
=> v12: Update NX, NY, DT

.editorconfig, gcm_regress.j, gcm_run.j, gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Supersedes #639 and #631 and #628 
---
Note: because this changes DT for some resolutions, it is non-zero-diff for that reason. For resolutions it doesn't change DT/LONG_DT for, it is probably zero-diff.
---
This PR updates NX, NY, and various DT per calculations by @wmputman
We also move to use even division on nodes at NCCS at NAS. This means 24, 40, and 120 cores per node on the various node types.
---
Testing by @wmputman and @pchakraborty on SLES15 at NCCS show that using:
```
setenv I_MPI_FABRICS shm:ofi
setenv I_MPI_OFI_PROVIDER psm3
```
is all that is needed. So this PR changes the flags on SLES15 to reflect this. For now it should keep the SLES12 flags as they were before.
This should be used only in concert with https://github.com/GEOS-ESM/GEOSgcm/pull/791 which moves GEOSgcm to …
=> v12: Update NX, NY, DT, Intel MPI Flags, OpenMP regress

CMakeLists.txt
This PR updates the ESMF CMake target to `ESMF::ESMF` which is the correct canonical target name for ESMF. This is necessary for Spack compatibility. NOTE: This requires ESMF 8.6.1 or later.
=> Update ESMF CMake target to ESMF::ESMF

.circleci/config.yml, gcm_forecast.tmpl, gcm_regress.j, gcm_run.j, gcm_run_benchmark.j
Recently, attempts to run v12 with the stretched grid failed (see https://github.com/GEOS-ESM/GEOSgcm/issues/824). Thanks to @wmputman he noticed that the run was trying to use the GWD ridge scheme (`NCAR_NRDG: 16`) but we don't have a C540 ridge file yet[^1], so we should use `NCAR_NRDG: 0` in that case.
This PR adds a run time "fix". When we try and copy over the ridge file, if it exists, we copy. If it doesn't, we change/append `NCAR_NRDG: 0` to the `AGCM.rc` in `scratch/`. 
[^1]: I believe @bena-nasa is trying to figure out how to get ridge files for all our other resolutions. When that happens, this code becomes moot.
=> v12: Add setting of NCAR_NRDG for resolutions without ridge files

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR brings in the updated Intel MPI flags for SLES15 at NCCS.
This is a precursor to moving v11 to Intel MPI. 
This is tested zero-diff to Open MPI
=> v11: Update Intel MPI flags

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
Closes #653 
This PR is an attempt to set the default ocean in the setup scripts (minus `gmichem_setup` which has a complex ocean selection) to choose Reynolds at C12 to C48 and then CS ocean at C90+.
I've also added a comment that the Reynolds ocean ends in 2022. I didn't add this comment to `gmichem_setup` since it's echo for ocean does a different thing. @mmanyin do you know when Reynolds starts? If so, I can update the script with the right range for Reynolds.
Keeping draft until I can test.
cc @sshakoor1 as he might as well do something similar in his Python variant.
=> v12: Fixes #653. Update default ocean to CS for C90+

scm_run.j, scm_setup
This is a PR with fixes for the SCM in v12. 
The changes are:
1. Use the git-v12.0 scm inputfiles which moves to GFDL microphysics by default
2. Move to 181 levels by default
3. Set some new sed bits
4. Copy over `fvcore_layout.rc` into `input.nml`
---
I'm keeping this draft until @narnold1 can test. It works for me in one case at least. If successful for him, we can merge and I can try it out in my nightly testing suite which runs all the cases
=> v12: Updates and fixes for SCM

.circleci/config.yml, AGCM.rc.tmpl
Closes #671 
This PR moves v12 to use a "generic" location for the RRTMGP files. 
Testing shows this works on bucy and at NAS.
=> v12: Move to use generic RRTMGP data location

scm_run.j, scm_setup
The SCM was broken in `develop` recently. Some fixes are done in the SCM datafile area, but this change needs to be in code.
It also turns on reading ExtData weights (if present). NOTE: This will *write* weights if not, but I hope to add the weights to all the SCM cases.
=> v11: Fixes for SCM

scm_setup
As part of #676, the ability to read file weights for ExtData was added.
What I unfortunately forgot to do was actually copy those weights into the experiments.
=> v11: Copy over weight files for SCM

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR adds the Cascade Lake nodes as allowed nodes. NOTE: This does *NOT* set up SLURM to use the current `sles15_cas` reservation, so users should add that themselves.
Also, we restore the two `I_MPI_ADJUST_` flags that have turned out to be needed still.
=> v11: Add Cas for SLES15; Add back IMPI flags on SLES15

gcm_setup, geoschemchem_setup, gmichem_setup, stratchem_setup
This PR adds the Cascade Lake nodes as allowed nodes. NOTE: This does NOT set up SLURM to use the current `sles15_cas` reservation, so users should add that themselves.
Also, we restore the two `I_MPI_ADJUST_` flags that have turned out to be needed still.
=> v12: Add Cas for SLES15; Add back IMPI flags on SLES15

.github/workflows/validate_yaml_files.yml, gcm_forecast.tmpl, gcm_regress.j, gcm_run.j, gcm_run_benchmark.j, gcm_setup, geoschemchem_setup, gmichem_setup, linkbcs.tmpl, stratchem_setup
Per @biljanaorescanin, for v13 BCs `gwd_internal_rst` is now carried in the BCs itself (as I guess the topo scripting makes it? cc @bena-nasa)
So, we need to handle things differently. We move the "copy rst to scratch/" bits into `linkbcs` as it knows where BCs are.
=> v12: Fixes for v13 gwd_internal_rst handling

AGCM.rc.tmpl
The @LDAS_INCR label is uncommented and set during setup for an LDAS/ADAS run.
=> Add label, @LDAS_INCR, to AGCM.rc.tmpl

gcm_forecast.tmpl, gcm_regress.j, gcm_run.j, gcm_run.j-new_rst_approach, gcm_run_benchmark.j
As found by @michellefrazer, the sed in our runscripts was not quite good. This code:
```csh
cat $instance.tmp | sed -e '/RRTMG/ s#RRTMG#RRTMGP#' > $instance
```
works great the first time around. But if you run multiple segments with the same scratch dir, well, you go from `RRTMG` to `RRTMGP` to `RRTMGPP` and boom, crash.
So we add word boundary markers to the sed to look only for the complete word `RRTMG`.
NOTE: The correct fix is to change the files in GOCART or do something smarter.
=> v12: Fix lazy sed for RRTMGP

CMakeLists.txt
Rather than make a user set a CMake option to use JeMalloc, let's just use CMake the way we should.
This should allow for easy use of JeMalloc if it's found.
Should be used in concert with https://github.com/GEOS-ESM/ESMA_env/pull/116
All tests show it zero-diff JeMalloc is enabled or not. Also, `gcm_regress.j` passes
---
Here is a chart of runs at `gcm_setup` defaults charting the Mem Comm number from the `AGCM Date` lines:
| Res  | Stock | Jemalloc |
|------|-------|----------|
| C24  | 42.5% | 26.1%    |
| C48  | 57.7% | 30.6%    |
| C90  | 53.8% | 31.0%    |
| C180 | 54.1% | 31.2%    |
=> v12: Support for easy Jemalloc

gcm_setup
This is a minor update for testing GEOSgcm with spack. Namely, we were too strict with assuming everything not NASA was a gmao desktop. For now, we use the fact we know GMAO desktops to set NX and NY to 1 and 6.
=> v12: Update for gcm_setup and spack

.github/workflows/workflow.yml, gcm_regress.j, gcm_run.j
This PR has two purposes.
1. Fix a bug in `gcm_run.j` when running with more than one OpenMP thread. This fix was already in `gcm_regress.j` but apparently was not ported to `gcm_run.j`
2. Update the `gcm_regress.j` script to use less resources
1. We now do 12 hour runs with a 3+9 for start-stop and 3 hr for layout and OpenMP
2. Change the layout run from 1-by-6 to NX-by-(NY/2)
I've also removed the `NUM_WRITERS` change in steps 4 and 5. It's causing some sort of issue, see https://github.com/GEOS-ESM/MAPL/issues/3687
=> v12: Update regress, fix bug in gcm_run for OpenMP
